use laboratorio;

SELECT * FROM NACIMIENTOS WHERE NACIONALIDAD LIKE 'EXTRANJERA';
SELECT * FROM NACIMIENTOS WHERE EDAD_MADRE < 18 ORDER BY EDAD_MADRE;
SELECT * FROM NACIMIENTOS WHERE EDAD_PADRE = EDAD_MADRE;
SELECT * FROM NACIMIENTOS WHERE EDAD_PADRE-EDAD_MADRE > 40;

SELECT * FROM CLIENTES_NEPTUNO WHERE PAIS = 'ARGENTINA';
SELECT * FROM CLIENTES_NEPTUNO WHERE PAIS NOT LIKE 'ARGENTINA' ORDER BY PAIS;

SELECT * FROM NACIMIENTOS WHERE SEMANAS < 20 ORDER BY SEMANAS DESC;
SELECT * FROM NACIMIENTOS WHERE SEXO = 'FEMENINO' AND NACIONALIDAD = 'EXTRANJERA' AND ESTADO_CIVIL_MADRE = 'SOLTERA' AND EDAD_MADRE > 40;

SELECT * FROM CLIENTES_NEPTUNO WHERE PAIS = 'Argentina' OR PAIS = 'Brasil' OR PAIS = 'Venezuela' ORDER BY PAIS, CIUDAD;

SELECT * FROM NACIMIENTOS WHERE SEMANAS BETWEEN 20 AND 25 ORDER BY SEMANAS;
SELECT * FROM NACIMIENTOS WHERE COMUNA 
IN (1101, 3201, 5605, 8108, 9204, 13120, 15202) ORDER BY COMUNA;

SELECT * FROM CLIENTES_NEPTUNO WHERE IDCliente LIKE 'C%';

SELECT * FROM NACIMIENTOS WHERE HIJOS_TOTAL > 10;

