use laboratorio;

SELECT COUNT(*) FROM PEDIDOS_NEPTUNO;
SELECT COUNT(TRANSPORTISTA) AS 'ENTREGAS SPEEDY EXPRESS' FROM PEDIDOS_NEPTUNO WHERE TRANSPORTISTA LIKE "%SPEEDY EXPRESS%";
SELECT COUNT(EMPLEADO) AS VENTAS FROM PEDIDOS_NEPTUNO WHERE EMPLEADO LIKE "C%";

SELECT ROUND(AVG(PRECIOUNIDAD), 2)AS "PRECIO PROMEDIO" FROM PRODUCTOS_NEPTUNO;
SELECT ROUND(AVG(PRECIOUNIDAD), 2)AS "PRECIO PROMEDIO", MIN(PRECIOUNIDAD) AS "PRECIO INFERIOR" FROM PRODUCTOS_NEPTUNO;
SELECT ROUND(AVG(PRECIOUNIDAD), 2)AS "PRECIO PROMEDIO", MIN(PRECIOUNIDAD) AS "PRECIO INFERIOR", MAX(PRECIOUNIDAD) AS "PRECIO MAXIMO" FROM PRODUCTOS_NEPTUNO;
SELECT MAX(PRECIOUNIDAD) AS "PRECIO MAXIMO", NOMBRECATEGORIA AS "CATEGORIA" FROM PRODUCTOS_NEPTUNO GROUP BY CATEGORIA;

SELECT TRANSPORTISTA, COUNT(IDPEDIDO) AS ENTREGAS FROM PEDIDOS_NEPTUNO GROUP BY TRANSPORTISTA;

SELECT SEXO, COUNT(SEXO) AS NACIMIENTOS FROM NACIMIENTOS GROUP BY SEXO;

SELECT NOMBRECOMPANIA AS CLIENTE, ROUND(SUM(CARGO), 2) AS "TOTAL GASTOS" FROM PEDIDOS_NEPTUNO GROUP BY NOMBRECOMPANIA;

SELECT SECCION, COUNT(COD_PRODUCTO) AS CANTIDAD FROM PRODUCTOS GROUP BY SECCION ORDER BY CANTIDAD DESC;

SELECT YEAR(FECHAPEDIDO) AS "AÑO", MONTHNAME(FECHAPEDIDO) AS "MES", COUNT(IDPEDIDO) AS VENTAS FROM PEDIDOS_NEPTUNO GROUP BY AÑO, MES ORDER BY AÑO,MONTH(FECHAPEDIDO);

SELECT EMPLEADO, ROUND(SUM(CARGO), 2) AS "FACTURACION", 
ROUND(AVG(CARGO), 2) AS "PROMEDIO",
MAX(CARGO) AS "MEJOR VENTA",
MIN(CARGO) AS "PEOR VENTA",
COUNT(IDPEDIDO) AS VENTAS
FROM PEDIDOS_NEPTUNO
GROUP BY EMPLEADO;



