DESC CLIENTES_NEPTUNO;

SELECT IDCLIENTE, NOMBRECOMPANIA, CONCAT(DIRECCION, " - ", CIUDAD, " - ",PAIS) AS UBICACION FROM CLIENTES_NEPTUNO;
SELECT IDCLIENTE, NOMBRECOMPANIA, CONCAT_WS(" - ", DIRECCION,CIUDAD,PAIS) AS UBICACION FROM CLIENTES_NEPTUNO;
SELECT IDCLIENTE, UPPER(NOMBRECOMPANIA) AS EMPRESA, CONCAT_WS(" - ", DIRECCION,CIUDAD,PAIS) AS UBICACION FROM CLIENTES_NEPTUNO;

SELECT FECHA, LEFT(SEXO, 1) AS SEXO, LEFT(TIPO_PARTO, 1) AS TIPO FROM NACIMIENTOS;

SELECT *, UPPER(CONCAT(LEFT(CIUDAD, 1), LEFT(PAIS, 1),RIGHT(PAIS, 2))) AS CODIGO FROM CLIENTES_NEPTUNO;

SELECT  SEXO, FECHA, TIPO_PARTO, ATENC_PART, LOCAL_PART,substring(FECHA, 4, 2) AS MES FROM NACIMIENTOS ORDER BY MES;
SELECT SEXO, FECHA, TIPO_PARTO, replace(NACIONALIDAD, "Chilena", "Ciudadana") NACIONALIDAD FROM NACIMIENTOS;
